regen

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -574,8 +574,8 @@ ac_unique_file="src/shell.in"
 ac_subst_vars='LTLIBOBJS
 LIBOBJS
 MANDOC_DOES_MARKDOWN
-COL
 MANDOC
+COL
 MKTEMP_TEMPLATE
 MKTEMP
 MAINT
@@ -2460,53 +2460,8 @@ unset _tmppath _tmpname
 
 
 # "mandoc" and "col" are used for generating the manuals.  These are
-# only needed if the distributed manuals are ever deleted or if the
-# source manual sources are updated.
-# Extract the first word of "mandoc", so it can be a program name with args.
-set dummy mandoc; ac_word=$2
-{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
-printf %s "checking for $ac_word... " >&6; }
-if test ${ac_cv_path_MANDOC+y}
-then :
-  printf %s "(cached) " >&6
-else
-  case $MANDOC in
-  [\\/]* | ?:[\\/]*)
-  ac_cv_path_MANDOC="$MANDOC" # Let the user override the test with a path.
-  ;;
-  *)
-  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  case $as_dir in #(((
-    '') as_dir=./ ;;
-    */) ;;
-    *) as_dir=$as_dir/ ;;
-  esac
-    for ac_exec_ext in '' $ac_executable_extensions; do
-  if as_fn_executable_p "$as_dir$ac_word$ac_exec_ext"; then
-    ac_cv_path_MANDOC="$as_dir$ac_word$ac_exec_ext"
-    printf "%s\n" "$as_me:${as_lineno-$LINENO}: found $as_dir$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-  done
-IFS=$as_save_IFS
-
-  ;;
-esac
-fi
-MANDOC=$ac_cv_path_MANDOC
-if test -n "$MANDOC"; then
-  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $MANDOC" >&5
-printf "%s\n" "$MANDOC" >&6; }
-else
-  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
-printf "%s\n" "no" >&6; }
-fi
-
-
+# only needed if the distributed manuals are ever deleted (e.g. using
+# "make distclean") or if the source manual sources are updated.
 # Extract the first word of "col", so it can be a program name with args.
 set dummy col; ac_word=$2
 { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
@@ -2552,18 +2507,56 @@ printf "%s\n" "no" >&6; }
 fi
 
 
-if test -z "$MANDOC" || test -z "$COL"
+# Extract the first word of "mandoc", so it can be a program name with args.
+set dummy mandoc; ac_word=$2
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
+printf %s "checking for $ac_word... " >&6; }
+if test ${ac_cv_path_MANDOC+y}
 then :
-  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: mandoc and/or col is missing, manuals can not be rebuilt" >&5
-printf "%s\n" "$as_me: WARNING: mandoc and/or col is missing, manuals can not be rebuilt" >&2;}
+  printf %s "(cached) " >&6
+else
+  case $MANDOC in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_MANDOC="$MANDOC" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  case $as_dir in #(((
+    '') as_dir=./ ;;
+    */) ;;
+    *) as_dir=$as_dir/ ;;
+  esac
+    for ac_exec_ext in '' $ac_executable_extensions; do
+  if as_fn_executable_p "$as_dir$ac_word$ac_exec_ext"; then
+    ac_cv_path_MANDOC="$as_dir$ac_word$ac_exec_ext"
+    printf "%s\n" "$as_me:${as_lineno-$LINENO}: found $as_dir$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+  done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+MANDOC=$ac_cv_path_MANDOC
+if test -n "$MANDOC"; then
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $MANDOC" >&5
+printf "%s\n" "$MANDOC" >&6; }
+else
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
+printf "%s\n" "no" >&6; }
 fi
 
-# Test whether "mandoc -T markdown" works.
-if test -n "$MANDOC" && test -n "$COL"
+
+if test -n "$MANDOC"
 then :
   { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking whether $MANDOC can produce markdown output" >&5
 printf %s "checking whether $MANDOC can produce markdown output... " >&6; }
-      if "$MANDOC" -T markdown </dev/null
+      if "$MANDOC" -T markdown </dev/null 2>/dev/null
 then :
   { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: yes" >&5
 printf "%s\n" "yes" >&6; }; MANDOC_DOES_MARKDOWN=1
@@ -2572,6 +2565,9 @@ else
 printf "%s\n" "no" >&6; };  MANDOC_DOES_MARKDOWN=0
 fi
 
+else
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: mandoc is missing, manuals can not be rebuilt" >&5
+printf "%s\n" "$as_me: WARNING: mandoc is missing, manuals can not be rebuilt" >&2;}
 fi
 
 ac_config_files="$ac_config_files Makefile src/Makefile doc/Makefile"
