Various
* Clean up function names.  I initially used a "_" prefix on some
  function names, but this is not needed (executive decision).

* Change _error() into errorf() and take answer to U&L question into
  account.  See https://unix.stackexchange.com/questions/438694

* Smaller changes to error messages.

* Prepare for a future when there may be more than one tool in the
  toolbox by setting UTIL to "shell" and using that in errorf() and the
  new output_version() function.  The UTIL variable may change name
  later.

diff --git a/src/shell.in b/src/shell.in
--- a/src/shell.in
+++ b/src/shell.in
@@ -3,11 +3,13 @@
 # Part of @PACKAGE_STRING@
 # For bug reports, see "@PACKAGE_BUGREPORT@"
 
+UTIL=shell
+
 # Variables set by the configure script:
 MKTEMP="@MKTEMP@"
 MKTEMP_TEMPLATE="@MKTEMP_TEMPLATE@"
 
-_error ()
+errorf ()
 {
     # Simple function for outputting error messages.  Prefixes the error
     # message with the name of the utility.
@@ -17,14 +19,27 @@ _error ()
     # stdout:       unused
     # stderr:       error message
 
-    printf 'shell: ' >&2
-
-    # We mimic printf here, disable shellcheck test.
-    # shellcheck disable=SC2059
-    printf "$@" >&2
+    # We mimic printf here, disable shellcheck warnings.
+    # See https://unix.stackexchange.com/questions/438694
+    # shellcheck disable=SC2059,SC2145
+    printf "$UTIL: ERROR: $@" >&2
 }
 
-_get_solaris_shells ()
+output_version ()
+{
+    # Simple function for outputting version information.
+
+    # Parameters:   none
+    # stdin:        unused
+    # stdout:       unused
+    # stderr:       version information
+
+    printf '%s: part of %s (release "%s")\n' \
+        "$UTIL" "@PACKAGE_NAME@" "@PACKAGE_VERSION@"
+    printf 'For bug reports, see %s\n' "@PACKAGE_BUGREPORT@"
+}
+
+get_solaris_shells ()
 {
     # Returns a list of valid Solaris 11.4 shells.  The list is taken
     # from the shells(4) manual and is shortened to only contain one
@@ -49,7 +64,7 @@ _get_solaris_shells ()
 END_LIST
 }
 
-_get_shells ()
+get_shells ()
 {
     # Returns a list of absolute paths to installed shells.  The shells
     # are validated (it's made sure that they are executable files)
@@ -73,11 +88,10 @@ _get_shells ()
        ! grep '^[^#]' /etc/shells 2>/dev/null
     then
         if [ "$( uname -s )" = "SunOS" ]; then
-            _get_solaris_shells
+            get_solaris_shells
         else
-            _error 'Can not get list of shells!\n'
-            _error 'Please file a bug report at\n'
-            _error '@PACKAGE_BUGREPORT@\n'
+            errorf 'Can not get list of shells!\n'
+            errorf 'Please file a bug report at\n%s\n' "@PACKAGE_BUGREPORT@"
             exit 1
         fi
     fi |
@@ -99,7 +113,7 @@ _exit_handler () {
 
 _usr1_handler () { keep=1; }
 
-force=0 # when 1, bypasses the call to _get_shells
+force=0 # when 1, bypasses the call to get_shells
 keep=0  # when 1, does not remove working directory when exiting
 while getopts 'd:fks:v' opt; do
     case "$opt" in
@@ -108,18 +122,16 @@ while getopts 'd:fks:v' opt; do
         f) force=1      ;;
         k) keep=1       ;;
         s) skel=$OPTARG ;;
-        v) printf 'shell: part of %s (release "%s")\n' \
-                "@PACKAGE_NAME@" "@PACKAGE_VERSION@"
-           printf 'For bug reports, see %s\n' "@PACKAGE_BUGREPORT@"
-           exit 0 ;;
-        *) _error 'error while parsing the command line\n'
+        v) output_version
+           exit 0       ;;
+        *) errorf 'Unknown option on command line\n'
            exit 1
     esac
 done
 shift "$(( OPTIND - 1 ))"
 
 if [ -n "$tmpwd" ] && [ -n "$skel" ]; then
-    _error 'Can not use both the -d and the -s option at the same time\n'
+    errorf 'Can not use both the -d and the -s option at the same time\n'
     exit 1
 fi
 
@@ -131,23 +143,23 @@ else
 fi
 
 if [ -z "$shell" ]; then
-    _error 'Can not determine what shell to start\n'
+    errorf 'Can not determine what shell to start\n'
     exit 1
 fi
 
 if [ "$force" -eq 0 ]; then
     # Get the absolute path to a real shell.  If multiple shells are
-    # returned from _get_shells, we will use the first one.
-    realshell="$( _get_shells | sed -n '\#/'"${shell##*/}"'$#{p;q;}' )"
+    # returned from get_shells, we will use the first one.
+    realshell="$( get_shells | sed -n '\#/'"${shell##*/}"'$#{p;q;}' )"
 
     if [ -z "$realshell" ]; then
-        _error 'No such shell: %s\n' "$shell"
+        errorf 'No such shell: %s\n' "$shell"
         echo 'Valid shells:' >&2
-        _get_shells | awk '{ printf("\t%s\n", $0) }' >&2
+        get_shells | awk '{ printf("\t%s\n", $0) }' >&2
         exit 1
     fi
 elif [ ! -x "$shell" ]; then
-        _error 'No such executable: %s\n' "$shell"
+        errorf 'No such executable: %s\n' "$shell"
         exit 1
 else
     realshell="$shell"
@@ -158,12 +170,12 @@ if [ -z "$tmpwd" ]; then
     tmpwd="$( "$MKTEMP" -d -t "$template" )"
 elif [ ! -d "$tmpwd" ]; then
     if [ -e "$tmpwd" ]; then
-        _error '"%s" exists, but is not a directory\n' "$tmpwd"
+        errorf '"%s" exists, but is not a directory\n' "$tmpwd"
         exit 1
     fi
 
     if ! mkdir -p "$tmpwd"; then
-        _error 'Failed to create directory "%s"\n' "$tmpwd"
+        errorf 'Failed to create directory "%s"\n' "$tmpwd"
         exit 1
     fi
 fi
@@ -173,7 +185,7 @@ trap _usr1_handler USR1
 
 if [ -n "$skel" ]; then
     if [ ! -d "$skel" ]; then
-        _error 'The -s option was used, but "%s" does not exist\n' "$skel"
+        errorf 'Can not find skeleton directory "%s"\n' "$skel"
         exit 1
     fi
 
@@ -183,7 +195,7 @@ if [ -n "$skel" ]; then
     elif command -v tar >/dev/null 2>&1; then
         tar -c -f - -C "$skel" . | tar -x -p -f - -C "$tmpwd"
     else
-        _error 'Can not use pax nor tar to copy "%s" to "%s"\n' "$skel" "$tmpwd"
+        errorf 'Can not use pax nor tar to copy "%s" to "%s"\n' "$skel" "$tmpwd"
         exit 1
     fi
 fi
