Turning shell functions into scripts

diff --git a/src/shtest.in b/src/shtest.in
--- a/src/shtest.in
+++ b/src/shtest.in
@@ -1,36 +1,35 @@
-function shtest
-{
-    # Will run the given command in all avaliable shells and capture and
-    # display the output generated on standard output as well as any
-    # diagnostic messages generated on standard error, together with the
-    # exit code.
-    #
-    # Example invocations:
-    #
-    #   $ shtest 'wc <( echo "hello" )'
-    #   $ shtest 'i=10; echo "$[ i - 1 ]"'
+#!@shell_path@
 
-    grep '^[^#]' /etc/shells | (
-    typeset -a tmpfiles
-    trap 'rm -f "${tmpfiles[@]}"' EXIT
-    while read realshell; do
-        typeset shell="${realshell##*/}"
+# Will run the given command in all avaliable shells and capture and
+# display the output generated on standard output as well as any
+# diagnostic messages generated on standard error, together with the
+# exit code.
+#
+# Example invocations:
+#
+#   $ shtest 'wc <( echo "hello" )'
+#   $ shtest 'i=10; echo "$[ i - 1 ]"'
 
-        typeset tmpout="$( mktemp -p /tmp "$shell-out.XXXXXXXX" )"
-        typeset tmperr="$( mktemp -p /tmp "$shell-err.XXXXXXXX" )"
+grep '^[^#]' /etc/shells | (
+typeset -a tmpfiles
+trap 'rm -f "${tmpfiles[@]}"' EXIT
+while read realshell; do
+    typeset shell="${realshell##*/}"
 
-        tmpfiles+=( "$tmpout" "$tmperr" )
+    typeset tmpout="$( mktemp -p /tmp "$shell-out.XXXXXXXX" )"
+    typeset tmperr="$( mktemp -p /tmp "$shell-err.XXXXXXXX" )"
 
-        command "$realshell" -c "$@" 1>"$tmpout" 2>"$tmperr"
-        err="$?"
+    tmpfiles+=( "$tmpout" "$tmperr" )
 
-        printf '=== %s (exit %d)\n' "$shell" "$err"
-        echo "--- stdout:"
-        cat "$tmpout"
-        echo "--- stderr:"
-        cat "$tmperr"
-    done )
-}
+    command "$realshell" -c "$@" 1>"$tmpout" 2>"$tmperr"
+    err="$?"
+
+    printf '=== %s (exit %d)\n' "$shell" "$err"
+    echo "--- stdout:"
+    cat "$tmpout"
+    echo "--- stderr:"
+    cat "$tmperr"
+done )
 
 
 # vim: ft=sh
